timeout: "120000"
spec:
  - test/**/*.test.ts
recursive: true
extension:
  - ts
loader:
  - ts-node/esm
import:
  # - ts-node/register.js
  - source-map-support/register.js
# import:
#   - tsx/esm
full-trace: true
exit: true
