timeout: "120000"
spec:
  - core/*/test/**/*.test.ts
  - plugin/*/test/**/*.test.ts
  - standalone/*/test/**/*.test.ts
  - test/**/*.test.ts
recursive: true
extension:
  - ts
require:
  - ts-node/register
  - source-map-support/register
full-trace: true
exit: true
