extends:
  - '@istanbuljs/nyc-config-typescript'
  - 'test-exclude'
all: true
check-coverage: true
temp-directory: './node_modules/.nyc_output'
report-dir: './coverage'
reporter:
  - text-summary
  - json-summary
  - json
  - lcov
lines: 0
statements: 0
exclude:
  - core/*/.autod.conf.js
  - core/*/typings
  - core/*/dist
  - plugin/*/.autod.conf.js
  - plugin/*/typings
  - plugin/*/dist
  - coverage
  - core/*/test/**/*
  - plugin/*/test/**/*
  - integration/*/test/**/*
  - standalone/*/test/**/*
  - benchmark/**/*
  - core/test-util/**/*
