packages:
  - core/*
  - plugin/*
  - standalone/*

catalog:
  '@eggjs/bin': beta
  '@eggjs/cookies': beta
  '@eggjs/mock': beta
  '@eggjs/rds': ^1.3.0
  '@eggjs/router': beta
  '@eggjs/tracer': beta
  '@eggjs/tsconfig': 3.1.0-beta.19
  '@eggjs/utils': beta
  '@sinclair/typebox': ^0.32.20
  '@types/js-beautify': ^1.14.3
  '@types/js-yaml': ^4.0.9
  '@types/koa-compose': ^3.2.5
  '@types/lodash': ^4.17.20
  '@types/lodash.snakecase': ^4.1.9
  '@types/mocha': ^10.0.10
  '@types/node': ^22.10.5
  '@types/nunjucks': ^3.2.6
  '@types/pluralize': ^0.0.33
  '@types/sqlstring': ^2.3.2
  '@vitest/coverage-v8': 4.0.0-beta.16
  ajv: ^8.17.1
  await-event: ^2.1.0
  await-first: ^1.0.0
  c8: ^10.1.3
  coffee: ^5.1.0
  egg: beta
  egg-errors: ^2.3.0
  egg-logger: ^3.0.1
  extend2: ^4.0.0
  globby: ^14.1.0
  is-type-of: ^2.2.0
  js-beautify: ^1.15.3
  js-yaml: 4.1.0
  koa-compose: ^4.1.0
  leoric: ^2.12.2
  lodash: ^4.17.21
  lodash.snakecase: ^4.1.1
  mm: ^4.0.2
  mocha: ^11.0.1
  mochawesome-with-mocha: ^8.0.0
  mysql2: ^3.12.0
  nunjucks: ^3.2.4
  oxlint: ^1.19.0
  oxlint-tsgolint: ^0.2.0
  path-to-regexp: ^1.9.0
  pluralize: ^8.0.0
  reflect-metadata: ^0.2.2
  rimraf: ^6.0.1
  sdk-base: ^5.0.1
  semver: ^7.7.2
  sqlstring: ^2.3.3
  tsdown: ^0.15.6
  tsx: ^4.20.6
  typescript: ^5.9.3
  unplugin-unused: ^0.5.3
  urllib: ^4.8.2
  vite: npm:rolldown-vite@^7.1.15
  vite-plugin-swc-transform: ^1.1.1
  vitest: 4.0.0-beta.16

catalogMode: prefer
