packages:
  - core/*
  - plugin/*
  - standalone/*

catalog:
  '@eggjs/bin': beta
  '@eggjs/mock': beta
  '@eggjs/rds': ^1.3.0
  '@eggjs/tracer': beta
  '@eggjs/tsconfig': beta
  '@eggjs/utils': beta
  '@types/lodash': ^4.17.20
  '@types/mocha': ^10.0.10
  '@types/node': ^22.10.5
  '@vitest/coverage-v8': 4.0.0-beta.16
  ajv: ^8.17.1
  c8: ^10.1.3
  coffee: ^5.1.0
  egg: beta
  egg-errors: ^2.3.0
  extend2: ^4.0.0
  globby: ^14.1.0
  is-type-of: ^2.2.0
  lerna: ^6.6.2
  mocha: ^11.0.1
  mochawesome-with-mocha: ^8.0.0
  oxlint: ^1.19.0
  oxlint-tsgolint: ^0.2.0
  reflect-metadata: ^0.2.2
  rimraf: ^6.0.1
  sdk-base: ^5.0.1
  tsdown: ^0.15.6
  tsx: ^4.20.6
  typescript: ^5.9.3
  unplugin-unused: ^0.5.3
  vite: npm:rolldown-vite@^7.1.15
  vite-plugin-swc-transform: ^1.1.1
  vitest: 4.0.0-beta.16

catalogMode: prefer
