name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm install
      - name: Prepare Release Env
        run: |
          if [[ "$GITHUB_REF" == *beta* ]]; then
            echo "IS_BETA=true" >> $GITHUB_ENV
          else
            echo "IS_BETA=false" >> $GITHUB_ENV
          fi
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          cat <<EOT >> .npmrc
          //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
          registry=https://registry.npmjs.org/
          always-auth=true
          EOT
          if [[ "$IS_BETA" == "true" ]]; then
            npx lerna publish from-git --dist-tag=beta --yes
          else
            npx lerna publish from-git --yes
          fi
